name: Scrape live deals (every 3 hours)

on:
  schedule:
    - cron: "0 */3 * * *"   # runs at minute 0, every 3rd hour
  workflow_dispatch:        # lets you run it manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TEQUILA_API_KEY: ${{ secrets.TEQUILA_API_KEY }}
      AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
      AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper_bot/requirements.txt

      - name: Run scraper
        run: |
          python scraper_bot/scrape.py

      - name: Commit updated JSON
        run: |
          git config user.name "scraper-bot"
          git config user.email "scraper-bot@users.noreply.github.com"
          git add data/live_deals.json
          git commit -m "Update live_deals.json [skip ci]" || echo "No changes to commit"
          git push
